source 'https://rubygems.org'

group :travis do
    gem 'kitchen-localhost', '0.3.0'
end

group :development do
    gem 'kitchen-vagrant', '~> 0.19'
    gem 'test-kitchen', '1.4.2'
    gem 'berkshelf', '4.0.1'
end
