Vagrant.configure("2") do |config|
  config.vm.synced_folder(
    '.',
    '<%= syncPath %>',
    :create => true,
    :group => 'vagrant',
    :owner => 'vagrant'
  )
  config.vm.define :ballotbox do |ballotbox|

    # There is a bug with synced folders: when :create and :owner are specified, the created parent folders are root-owned rather
    # than owned by :owner. 

    ballotbox.vm.provision "shell", 
        inline: "chown -R vagrant:vagrant <%= syncPath %>"
        
    ballotbox.vm.box = 'ubuntu-trusty'
    ballotbox.vm.box_url = 'https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box'
    ballotbox.vm.network :private_network, type: :dhcp
    ballotbox.berkshelf.enabled = true

    config.berkshelf.berksfile_path = 'cookbooks/Berksfile'
    config.omnibus.chef_version = :latest

    ballotbox.vm.provision :chef_zero do |chef|
      chef.cookbooks_path = 'cookbooks'

      chef.add_recipe '<%= name %>::default'
   end
  end
end

